cylinder {
   <0.356822,0,-0.934172>,
   <0.57735,-0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.356822,0,-0.934172>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.57735,-0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <0.57735,0.57735,-0.57735>,
   <0.356822,0,-0.934172>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.57735,0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.356822,0,-0.934172>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <-0.356822,0,-0.934172>,
   <-0.57735,0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.356822,0,-0.934172>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.57735,0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <-0.57735,-0.57735,-0.57735>,
   <0,-0.934172,-0.356822>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.57735,-0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0,-0.934172,-0.356822>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <-0.57735,0.57735,0.57735>,
   <-0.356822,0,0.934172>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.57735,0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.356822,0,0.934172>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <-0.934172,-0.356822,0>,
   <-0.57735,-0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.934172,-0.356822,0>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.57735,-0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <-0.57735,-0.57735,-0.57735>,
   <-0.356822,0,-0.934172>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.57735,-0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.356822,0,-0.934172>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <-0.356822,0,0.934172>,
   <0.356822,0,0.934172>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.356822,0,0.934172>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.356822,0,0.934172>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <0.57735,-0.57735,0.57735>,
   <0.356822,0,0.934172>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.57735,-0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.356822,0,0.934172>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <-0.57735,-0.57735,0.57735>,
   <-0.934172,-0.356822,0>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.57735,-0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.934172,-0.356822,0>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <0.356822,0,0.934172>,
   <0.57735,0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.356822,0,0.934172>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.57735,0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <0,-0.934172,0.356822>,
   <-0.57735,-0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0,-0.934172,0.356822>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.57735,-0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <-0.356822,0,-0.934172>,
   <0.356822,0,-0.934172>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.356822,0,-0.934172>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.356822,0,-0.934172>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <0,-0.934172,-0.356822>,
   <0,-0.934172,0.356822>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0,-0.934172,-0.356822>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0,-0.934172,0.356822>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <-0.356822,0,0.934172>,
   <-0.57735,-0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.356822,0,0.934172>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.57735,-0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <0.57735,-0.57735,0.57735>,
   <0,-0.934172,0.356822>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.57735,-0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0,-0.934172,0.356822>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <0.934172,-0.356822,0>,
   <0.57735,-0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.934172,-0.356822,0>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.57735,-0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <0.57735,-0.57735,-0.57735>,
   <0.934172,-0.356822,0>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.57735,-0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.934172,-0.356822,0>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <0,-0.934172,-0.356822>,
   <0.57735,-0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0,-0.934172,-0.356822>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.57735,-0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <0.934172,-0.356822,0>,
   <0.934172,0.356822,0>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.934172,-0.356822,0>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.934172,0.356822,0>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <0,0.934172,-0.356822>,
   <0,0.934172,0.356822>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0,0.934172,-0.356822>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0,0.934172,0.356822>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <0,0.934172,0.356822>,
   <0.57735,0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0,0.934172,0.356822>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.57735,0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <0.57735,0.57735,0.57735>,
   <0.934172,0.356822,0>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.57735,0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.934172,0.356822,0>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <0.934172,0.356822,0>,
   <0.57735,0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.934172,0.356822,0>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.57735,0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <0.57735,0.57735,-0.57735>,
   <0,0.934172,-0.356822>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0.57735,0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0,0.934172,-0.356822>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <-0.934172,-0.356822,0>,
   <-0.934172,0.356822,0>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.934172,-0.356822,0>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.934172,0.356822,0>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <0,0.934172,-0.356822>,
   <-0.57735,0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0,0.934172,-0.356822>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.57735,0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <-0.57735,0.57735,-0.57735>,
   <-0.934172,0.356822,0>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.57735,0.57735,-0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.934172,0.356822,0>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <-0.934172,0.356822,0>,
   <-0.57735,0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.934172,0.356822,0>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.57735,0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
cylinder {
   <-0.57735,0.57735,0.57735>,
   <0,0.934172,0.356822>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <-0.57735,0.57735,0.57735>,
   RADIUS
   texture { dodectexture }
}
sphere {
   <0,0.934172,0.356822>,
   RADIUS
   texture { dodectexture }
}
