cylinder {
   <0,-0.52573,0.850652>,
   <-0.52573,-0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,-0.52573,0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.52573,-0.850652,0>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0.52573,-0.850652,0>,
   <0,-0.52573,0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.52573,-0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,-0.52573,0.850652>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <-0.850652,0,0.52573>,
   <-0.52573,-0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.850652,0,0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.52573,-0.850652,0>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0,0.52573,0.850652>,
   <-0.850652,0,0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,0.52573,0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.850652,0,0.52573>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0.52573,-0.850652,0>,
   <0.850652,0,0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.52573,-0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.850652,0,0.52573>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0.850652,0,0.52573>,
   <0,-0.52573,0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.850652,0,0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,-0.52573,0.850652>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0.52573,-0.850652,0>,
   <0,-0.52573,-0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.52573,-0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,-0.52573,-0.850652>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <-0.52573,0.850652,0>,
   <-0.850652,0,0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.52573,0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.850652,0,0.52573>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0.850652,0,-0.52573>,
   <0.52573,-0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.850652,0,-0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.52573,-0.850652,0>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0,0.52573,-0.850652>,
   <-0.850652,0,-0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,0.52573,-0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.850652,0,-0.52573>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0,0.52573,-0.850652>,
   <-0.52573,0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,0.52573,-0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.52573,0.850652,0>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <-0.850652,0,-0.52573>,
   <-0.52573,0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.850652,0,-0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.52573,0.850652,0>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0.850652,0,0.52573>,
   <0.850652,0,-0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.850652,0,0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.850652,0,-0.52573>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0,0.52573,0.850652>,
   <0.850652,0,0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,0.52573,0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.850652,0,0.52573>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0,-0.52573,-0.850652>,
   <-0.52573,-0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,-0.52573,-0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.52573,-0.850652,0>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <-0.850652,0,0.52573>,
   <0,-0.52573,0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.850652,0,0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,-0.52573,0.850652>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0.52573,0.850652,0>,
   <0,0.52573,-0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.52573,0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,0.52573,-0.850652>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0.850652,0,-0.52573>,
   <0.52573,0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.850652,0,-0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.52573,0.850652,0>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <-0.52573,0.850652,0>,
   <0.52573,0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.52573,0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.52573,0.850652,0>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0.850652,0,-0.52573>,
   <0,-0.52573,-0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.850652,0,-0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,-0.52573,-0.850652>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0,0.52573,-0.850652>,
   <0.850652,0,-0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,0.52573,-0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.850652,0,-0.52573>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0,-0.52573,-0.850652>,
   <0,0.52573,-0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,-0.52573,-0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,0.52573,-0.850652>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <-0.850652,0,-0.52573>,
   <0,-0.52573,-0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.850652,0,-0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,-0.52573,-0.850652>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0.52573,0.850652,0>,
   <0,0.52573,0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.52573,0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,0.52573,0.850652>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <-0.52573,-0.850652,0>,
   <0.52573,-0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.52573,-0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.52573,-0.850652,0>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0,0.52573,0.850652>,
   <-0.52573,0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,0.52573,0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.52573,0.850652,0>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0.52573,0.850652,0>,
   <0.850652,0,0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.52573,0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0.850652,0,0.52573>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <-0.52573,-0.850652,0>,
   <-0.850652,0,-0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.52573,-0.850652,0>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.850652,0,-0.52573>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <0,0.52573,0.850652>,
   <0,-0.52573,0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,0.52573,0.850652>,
   RADIUS
   texture { icostexture }
}
sphere {
   <0,-0.52573,0.850652>,
   RADIUS
   texture { icostexture }
}
cylinder {
   <-0.850652,0,0.52573>,
   <-0.850652,0,-0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.850652,0,0.52573>,
   RADIUS
   texture { icostexture }
}
sphere {
   <-0.850652,0,-0.52573>,
   RADIUS
   texture { icostexture }
}
