cylinder {
   <1,0,0>,
   <0,-1,0>,
   RADIUS
   texture { octatexture }
}
sphere {
   <1,0,0>,
   RADIUS
   texture { octatexture }
}
sphere {
   <0,-1,0>,
   RADIUS
   texture { octatexture }
}
cylinder {
   <0,-1,0>,
   <0,0,1>,
   RADIUS
   texture { octatexture }
}
sphere {
   <0,-1,0>,
   RADIUS
   texture { octatexture }
}
sphere {
   <0,0,1>,
   RADIUS
   texture { octatexture }
}
cylinder {
   <0,1,0>,
   <0,0,-1>,
   RADIUS
   texture { octatexture }
}
sphere {
   <0,1,0>,
   RADIUS
   texture { octatexture }
}
sphere {
   <0,0,-1>,
   RADIUS
   texture { octatexture }
}
cylinder {
   <-1,0,0>,
   <0,1,0>,
   RADIUS
   texture { octatexture }
}
sphere {
   <-1,0,0>,
   RADIUS
   texture { octatexture }
}
sphere {
   <0,1,0>,
   RADIUS
   texture { octatexture }
}
cylinder {
   <0,0,1>,
   <1,0,0>,
   RADIUS
   texture { octatexture }
}
sphere {
   <0,0,1>,
   RADIUS
   texture { octatexture }
}
sphere {
   <1,0,0>,
   RADIUS
   texture { octatexture }
}
cylinder {
   <0,0,1>,
   <-1,0,0>,
   RADIUS
   texture { octatexture }
}
sphere {
   <0,0,1>,
   RADIUS
   texture { octatexture }
}
sphere {
   <-1,0,0>,
   RADIUS
   texture { octatexture }
}
cylinder {
   <0,1,0>,
   <0,0,1>,
   RADIUS
   texture { octatexture }
}
sphere {
   <0,1,0>,
   RADIUS
   texture { octatexture }
}
sphere {
   <0,0,1>,
   RADIUS
   texture { octatexture }
}
cylinder {
   <1,0,0>,
   <0,1,0>,
   RADIUS
   texture { octatexture }
}
sphere {
   <1,0,0>,
   RADIUS
   texture { octatexture }
}
sphere {
   <0,1,0>,
   RADIUS
   texture { octatexture }
}
cylinder {
   <-1,0,0>,
   <0,-1,0>,
   RADIUS
   texture { octatexture }
}
sphere {
   <-1,0,0>,
   RADIUS
   texture { octatexture }
}
sphere {
   <0,-1,0>,
   RADIUS
   texture { octatexture }
}
cylinder {
   <0,-1,0>,
   <0,0,-1>,
   RADIUS
   texture { octatexture }
}
sphere {
   <0,-1,0>,
   RADIUS
   texture { octatexture }
}
sphere {
   <0,0,-1>,
   RADIUS
   texture { octatexture }
}
cylinder {
   <0,0,-1>,
   <1,0,0>,
   RADIUS
   texture { octatexture }
}
sphere {
   <0,0,-1>,
   RADIUS
   texture { octatexture }
}
sphere {
   <1,0,0>,
   RADIUS
   texture { octatexture }
}
cylinder {
   <0,0,-1>,
   <-1,0,0>,
   RADIUS
   texture { octatexture }
}
sphere {
   <0,0,-1>,
   RADIUS
   texture { octatexture }
}
sphere {
   <-1,0,0>,
   RADIUS
   texture { octatexture }
}
